# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
# the id should be lowercase made up of "ihe." + {domain acronym} + "." + {profile acronym/short-name}
# e.g. ihe.iti.mhds, or ihe.iti.basicaudit
id: fhir.nw-gmsa.nhs.uk
canonical: https://fhir.nw-gmsa.nhs.uk
version: 0.0.1
name: NWEngland_IHELTW
title: North West Genomic Medicine Service Alliance - Testing Workflow (LTW)
description: NHS England North West Genomic Medicine Service Alliance - IHE Laboratory Testing Workflow (LTW)
releaseLabel: ci-build

status: draft
publisher:
  ## Find your domain contact on the https://www.ihe.net/ihe_domains page
  - name: NHS England North West GMSA
  - url: https://www.nw-gmsa.nhs.uk/contact-us

license:  CC-BY-4.0
fhirVersion: 4.0.1
jurisdiction: urn:iso:std:iso:3166#GB "United Kingdom of Great Britain and Northern Ireland"

#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2024+

dependencies:
  fhir.r4.ukcore.stu3.currentbuild:
    version: 0.0.19-pre-release
    uri: https://simplifier.net/guide/ukcoreversionhistory
  hl7.fhir.extensions.r5:
    id: r5ext
    version: 4.0.1
    reason:
      Makes available certain R5 elements for use as part of this R4 IG
  hl7.fhir.eu.laboratory:
    version: 0.1.1
  hl7.fhir.uv.sdc:
    version: 3.0.0

FSHOnly: false
# see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
parameters:
  path-binary: input/attachments
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
  excludexml: 'false'
  excludettl: 'true'
  excludemap: 'true'
  generate:
    - xml
    - json
  path-expansion-params: '../resources/Parameters-exp-params.json'


#resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true
instanceOptions:
  setMetaProfile: never


pages:
  index.md:
    title: Home
    generation: markdown
  LTW.md:
    title: Laboratory Testing Workflow (LTW)
    generation: markdown
  PIX.md:
    title: Patient Identifier Cross-referencing (PIX)
    generation: markdown
  HPD.md:
    title: Healthcare Provider Directory (HPD)
    generation: markdown
  HIE.md:
    title: Health Information Exchange (HIE)
    generation: markdown
  LAB-1.md:
    title: Placer Order Management [LAB-1]
    generation: markdown
  LAB-2.md:
    title: Filler Order Management [LAB-2]
    generation: markdown
  LAB-3.md:
    title: Order Results Management [LAB-3]
    generation: markdown
  LAB-4.md:
    title: Work Order Management [LAB-4]
    generation: markdown
  LAB-5.md:
    title: Test Results Management [LAB-5]
    generation: markdown
  DDD-TestOrder.md:
    title: Genomic Test Order
    generation: markdown
  DDD-TestReport.md:
    title: Genomic Test Report
    generation: markdown
  DDD-Overview.md:
    title: Overview
    generation: markdown
  hl7v2.md:
    title: HL7 v2 Artefacts
    generation: markdown
  architecture.md:
    title: Architecture
    generation: markdown
  testing.md:
    title: Testing
    generation: markdown
  support.md:
    title: Support
    generation: markdown
  authorisation.md:
    title: Authorisation (OAuth2)
    generation: markdown

resources:
  Questionnaire/GenomicTestOrder:
    name: North West Genomics Test Order
    description: NHS England North West Genomics Test Order (Draft)
    exampleBoolean: false
  Questionnaire/81247-9:
    name: Master HL7 genetic variant reporting panel
    description: Master HL7 genetic variant reporting panel [Questionnaire Viewer](https://project-wildfyre.github.io/questionnaire-viewer/?q=https:%2F%2Fraw.githubusercontent.com%2FInterop-NWEngland%2FLTW-Genomics%2Frefs%2Fheads%2Fmain%2Finput%2Fresources%2FMaster-HL7-genetic-variant-reporting-panel.R4.json)
    exampleBoolean: false

menu:
  Home: index.html
  Analysis and Design (Vol 1) :
    Laboratory Testing Workflow (LTW): LTW.html
    Patient Identifier Cross-referencing (PIX): PIX.html
    Authorisation (OAuth2): authorisation.html
##    Health Information Exchange (HIE): HIE.html
  Interfaces (Vol 2):
    Placer Order Management [LAB-1]: LAB-1.html
##    Filler Order Management [LAB-2]: LAB-2.html
    Order Results Management [LAB-3]: LAB-3.html
##    Work Order Management [LAB-4]: LAB-4.html
##    Test Results Management [LAB-5]: LAB-5.html
  Domain Archetypes:
    Overview: DDD-Overview.html
    Genomic Test Order: DDD-TestOrder.html
    Genomic Test Report: DDD-TestReport.html
  Artefacts: artifacts.html
  HL7 v2 Artefacts: hl7v2.html
  Development:
    Architecture: architecture.html
    Testing: testing.html
    Support: support.html

groups:
  -ex-example-laboratory-order:
    name: "Example: Laboratory Order"
    description: "Laboratory Order Examples"
    resources:
      - Binary/0a898233-763c-405d-8172-8c4f07e6e636
      - Bundle/GenomicsOrderMessageAcknowledgement
      - Bundle/GenomicsOrderMessageAttachment
      - Bundle/GenomicsOrderMessageCodedEntries
      - Bundle/GenomicsOrderSearchSet
      - DocumentReference/a293b4a6-e46b-4402-9b2b-d9517afc7137
      - Encounter/984b8a89-4194-4eb4-a7ea-ca8049ebeea3
      - MessageHeader/MessageHeaderGenomicOrder
      - MessageHeader/MessageHeaderGenomicOrderAcknowledgement
      - QuestionnaireResponse/QuestionnaireResponseOrderEntryExample
      - Patient/Patient-OctaviaCHISLETT-9449305552
      - PractitionerRole/ee9b8fcc-c233-43e1-b7fb-b58ce4cf1db8
      - ServiceRequest/ServiceRequestGenomicsOrderCodedEntries
      - ServiceRequest/ServiceRequestGenomicsOrderAttachment
      - Specimen/SpecimenExample
  -ex-example-laboratory-report:
    name: "Example: Laboratory Report"
    description: "Laboratory Report Examples"
    resources:
      - Binary/d6eeedd1-92d3-45b9-bf33-6401e804425f
      - Bundle/GenomicsReportMessage
      - DiagnosticReport/DiagnosticReportGenomicsReport
      - DocumentReference/94bf65ba-cd6c-4601-b339-6d547f424646
      - MessageHeader/MessageHeaderGenomicReport
  -ex-example-other:
    name: "Example: Ask at Order Entry questions and prior results"
    description: " Ask at Order Entry questions and prior results"
    resources:
      - Bundle/FHIRDocumentGeneticReportBundle
      - Composition/Composition-GenomicsReport-OctaviaCHISLETT
      - Observation/EPIC-OBR-1
      - Observation/OBX-GenomicReferralCategory
      - Observation/OBX-SupervisingClinician
      - Observation/OBX-Pregnancy
      - Observation/OBX-HighInfectionRiskSample
      - Observation/OBX-InformedConsent
      - Observation/EPIC-OBX-4
      - Observation/EPIC-OBX-2
      - Observation/EPIC-OBX-6
      - Observation/EPIC-OBX-7
      - Observation/EPIC-OBX-2
      - Observation/EPIC-OBX-8
      - Observation/EPIC-OBX-10
      - Observation/EPIC-OBX-11

